# example configuration file for windows_exporter

collectors:
  enabled: cpu,cpu_info,exchange,iis,logical_disk,logon,memory,net,os,process,remote_fx,service,system,tcp,time,terminal_services,textfile
collector:
  service:
    include: "windows_exporter"
log:
  level: warn
